pull_request_rules:
  - name: Automatic merge on Status Checks passing
    conditions:
      - title~=^\[Snyk\]
      - head~=^snyk-fix
      - "check-success ~= .*"
    actions:
      merge:
        method: squash
