language: node_js
node_js:
  - "8"
  - "10"
  - "12"
before_script:
  - yarn run lint
install:
  - yarn install
  - yarn global add codecov
script:
  - yarn run test
  - codecov
after_success:
  - yarn run semantic-release
